### ISSUE TITLE
Best way to run the program from the Linux CLI?

### ISSUE THREAD

**Issue by AusDavo** [mycitadel/mycitadel-desktop#33]
## Bug type
Put `x` in the boxes below:
- [x] Installation issue
- [ ] App crash
- [ ] Broken UI
- [ ] Incorrect app behaviour

## Operating system
- [x] Linux (specify distribution here)
- [ ] MacOS
- [ ] Windows

## Problem description
Please, what is the best way to run the program from the Linux CLI? The guide says, "Finally, download executable from the list below and run it." I have downloaded the file but I can't see how to run it.

## Attachments

No attachment.

**Comment by AusDavo** [comment]
I'm going to try compiling from the source instead.

I installed Rust.

I used `cargo install mycitadel-linux-amd64 --locked`

Now, the program is fetching something. I'll post again with how it turns out.

**Comment by AusDavo** [comment]
```
~/Downloads$ cargo install mycitadel-linux-amd64 --locked    Updating crates.io index
error: could not find `mycitadel-linux-amd64` in registry `crates-io` with version `*`
```
I'm stuck :(

**Comment by AusDavo** [comment]
I re-tried the advised command `cargo install mycitadel-desktop --locked` again.* Now, I think that it's working...

*The first time, I got an error:

```
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
```

**Comment by AusDavo** [comment]
Downloading lots. Compiling lots. Throwing a few of these too `error[E0277]`. Concluded with the following:

```
For more information about this error, try `rustc --explain E0277`.
error: could not compile `bitcoin_hd` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mycitadel-desktop v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installUqnwsx`

Caused by:
  build failed

```

**Comment by AusDavo** [comment]
I'll try compiling again...

**Comment by AusDavo** [comment]
Still stuck. Busting to try the software though. It looks awesome. I'll check in again soon.

**Comment by dr-orlovsky** [comment]
Can you please provide the details on where `error[E0277]` happens in `bitcoin_id`? I.e. the end of the build log with the error messages.

**Comment by dr-orlovsky** [comment]
Happy that you've managed to get it working! Do not worry about console messages, these are GTK UI-related messages of no importance to the app.
