### ISSUE TITLE
Ubuntu 20.04 libc version incompatibility

### ISSUE THREAD

**Issue by Overtorment** [mycitadel/mycitadel-desktop#34]
## Bug type
Put `x` in the boxes below:
- [x] Installation issue
- [ ] App crash
- [ ] Broken UI
- [ ] Incorrect app behaviour

## Operating system
- [x] Linux
- [ ] MacOS
- [ ] Windows

## Problem description

```
overtorment@hostname:~/Downloads$ ./mycitadel-linux-amd64 
./mycitadel-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./mycitadel-linux-amd64)
./mycitadel-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./mycitadel-linux-amd64)
./mycitadel-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./mycitadel-linux-amd64)
./mycitadel-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./mycitadel-linux-amd64)
```

all deps mentioned on release page for linux were installed.

```
$ uname -a
Linux hostname 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 5.1.7 Hera
Release:        5.1.7
Codename:       hera
```

**Comment by AusDavo** [comment]
I'm going to try compiling from source using rust now.

**Comment by dr-orlovsky** [comment]
Hm, haven't tried it under elementary. But looks like the `glibc` library is missed. Can you try `sudo apt install glibc`?

**Comment by dr-orlovsky** [comment]
1. Maybe try `apt-get update apt-get install build-essential -y`
2. Seems like you/ElementaryOS has a different glibc version than 2.29. You can check your current version with `dpkg -l libc-bin`

**Comment by Overtorment** [comment]
```
$ dpkg -l libc-bin
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                     Version                           Architecture                      Description
+++-========================================================-=================================-=================================-======================================================================================================================
ii  libc-bin                                                 2.27-3ubuntu1.5                   amd64                             GNU C Library: Binaries

```

**Comment by dr-orlovsky** [comment]
Yeah, the version is old (2.27 < 2.29, required at least). I tried to google how to update it, but failed to find a solution. Will keep looking tomorrow.

**Comment by Overtorment** [comment]
appimage for linux would be awesome!

**Comment by dr-orlovsky** [comment]
We are working on flatpak distribution, will you prefer it, or still would like to have AppImage?

**Comment by globule** [comment]
It seem libc 2.33 is required on Neon (Ubuntu based) upd to date
$ ./mycitadel-linux-amd64
./mycitadel-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./mycitadel-linux-amd64)
$ dpkg -l libc-bin
...
ii  libc-bin       2.31-0ubuntu9.7 amd64        GNU C Library: Binaries

**Comment by Overtorment** [comment]
flatpak is good enough, thanks!

**Comment by dr-orlovsky** [comment]
Yes, we confirm that Ubuntu 20.04 has the same issue, and it looks unfixable without distro upgrade. It affects many other software.

Looking for a solution on how we can pack the needed version of `glibc` library together with the program.

**Comment by dpc** [comment]
Not having to deal with glibc is why I always try to build my Rust project release binaries for Linux with musl toolchain. However, I doubt it will work for gtk app.

Seems like the best practical solution is:

> Yes, the easiest way to support old glibc is to build the applications on a older setup.

https://stackoverflow.com/a/14291014

If you link against old glibc, it will work on any system with glibc that is the same or newer.

**Comment by dr-orlovsky** [comment]
Seems like no viable solution can be found for the issue, and with more ppl moving to more recent Ubuntu releases (it's been exactly 3 years after 20.04 release) I think we can close this issue as an impossible to fix
