### ISSUE TITLE
Desktop  build on Linux fails with compile errors

### ISSUE THREAD

**Issue by btcschellingpt** [mycitadel/mycitadel-desktop#39]
## Bug type
Put `x` in the boxes below:
- [x] Installation issue
- [ ] App crash
- [ ] Broken UI
- [ ] Incorrect app behaviour

## Operating system
- [x] Linux Ubuntu 20.04 Desktop fully patched
- [ ] MacOS
- [ ] Windows

## Problem description
Attempted to build using: cargo install mycitadel-desktop --locked

Results:
   ...
   Compiling slip132 v0.7.0
   Compiling bitcoin_scripts v0.7.0
   Compiling bitcoin_hd v0.7.0
error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 3]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/indexes.rs:854:29
    |
854 |             s if s.contains(&['-', ',', ';']) => IndexRangeList::from_str(s)?.into(),
    |                    -------- ^^^^^^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 3]`
    |                    |
    |                    required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 3]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 3]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 3]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:224:32
    |
224 |             let sp = s.replace(&['\'', 'h'], "");
    |                        ------- ^^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:239:32
    |
239 |         let s = if s.ends_with(&['h', '\'']) {
    |                      --------- ^^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |                      |
    |                      required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:241:35
    |
241 |                 .trim_end_matches(&['h', '\''])
    |                  ---------------- ^^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |                  |
    |                  required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:251:33
    |
251 |             .trim_start_matches(&['<', '{'])
    |              ------------------ ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:252:31
    |
252 |             .trim_end_matches(&['>', '}']);
    |              ---------------- ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:253:29
    |
253 |         for item in s.split(&[',', ';']) {
    |                       ----- ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |                       |
    |                       required by a bound introduced by this call
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
   --> /home/wizardofaus/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.0/src/ranges.rs:253:23
    |
253 |         for item in s.split(&[',', ';']) {
    |                       ^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bitcoin_hd` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mycitadel-desktop v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installyKWWUB`

**Comment by dr-orlovsky** [comment]
I expect you are using outdated rust version. Please do `rustup update` and `rustup default stable`

**Comment by btcschellingpt** [comment]
Thanks - this was correct and I resolved this on Ubuntu 20.04 by:

1. Removing the current binaries which were causing the problem using: sudo apt remove cargo
2. Then applying the suggested: rustup update && restup default stable
3. Then running the referenced script to build: cargo install mycitadel-desktop --locked

The original suggestion to update rust fails on Ubuntu 20.04 unless prior version (without rustup) removed first.
Thanks for your help; issue can be closed.

**Comment by dr-orlovsky** [comment]
I will keep the issue opened until I will add this instructions from you to the README. Thank you for finding and describing the solution!

**Comment by dr-orlovsky** [comment]
Now we have a `toolchain.toml` file which should prevent the issue from happening. I also have added instructions to `INSTALL.md` on how to fix problems of that sort.
