### ISSUE TITLE
Verification of binaries

### ISSUE THREAD

**Issue by felipebrunet** [mycitadel/mycitadel-desktop#44]
Hi, 
It would be great if you could post your pubkey fingerprint, or upload your Pubkey?

I found This Pubkey (asociated to your published protonmail address) in Ubuntu Keyserver:

Link: https://keyserver.ubuntu.com/pks/lookup?search=orlovsky%40protonmail.ch&fingerprint=on&op=index

pub [dsa2048/fbdea8433ddc1e69fa90c35effc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xfbdea8433ddc1e69fa90c35effc0250947e5c6f7) 2020-09-28T15:44:31Z
	 Hash=[ffd664a623e312ea9e4ddda13b8ca758](https://keyserver.ubuntu.com/pks/lookup?op=hget&search=ffd664a623e312ea9e4ddda13b8ca758)

uid Dr Maxim Orlovsky <orlovsky@pandoraprime.ch>
sig  sig  [ffc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xffc0250947e5c6f7) 2022-05-04T15:35:24Z ____________________ ____________________ [[selfsig]](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xffc0250947e5c6f7)

uid Dr Maxim Orlovsky <orlovsky@mycitadel.io>
sig  sig  [ffc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xffc0250947e5c6f7) 2022-05-04T15:35:09Z ____________________ ____________________ [[selfsig]](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xffc0250947e5c6f7)

uid Dr Maxim Orlovsky <orlovsky@pandoracore.com>
sig  sig  [ffc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xffc0250947e5c6f7) 2020-09-28T15:52:54Z ____________________ ____________________ [[selfsig]](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xffc0250947e5c6f7)

uid Dr Maxim Orlovsky <orlovsky@lnp-bp.org>
sig  sig  [ffc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xffc0250947e5c6f7) 2020-09-28T15:51:47Z ____________________ ____________________ [[selfsig]](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xffc0250947e5c6f7)

uid Dr Maxim Orlovsky <orlovsky@protonmail.ch>
sig  sig  [ffc0250947e5c6f7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xffc0250947e5c6f7) 2020-09-28T15:44:31Z ____________________ ____________________ [[selfsig]](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xffc0250947e5c6f7)

Finally, is it possible if you could also upload a file with the hashes of the binaries, and a signature of the whole message please?

Thanks.

**Comment by dr-orlovsky** [comment]
I confirm that the key is correct. The fingerprint is present in the About screen of the app; will be also dding it to the release descriptors.

Currently the binary builds contain a single file per platform, so there was no reason for a separate manifest. With the next release we will switch to installers and will provide manifests.

**Comment by harrymmmm** [comment]
The signed file in v1.1.0 (the .asc file, 8MB) contains an attached signature of something, but it doesn't verify the actual binary (16MB) offered for download. The normal way to do this is to provide a detached signature of the actual binary or (as you mention above) a signed file of the hashes of the offered release binaries.

**Comment by felipebrunet** [comment]
> The signed file in v1.1.0 (the .asc file, 8MB) contains an attached signature of something, but it doesn't verify the actual binary (16MB) offered for download. The normal way to do this is to provide a detached signature of the actual binary or (as you mention above) a signed file of the hashes of the offered release binaries.

Yes, that is how signatures are made at bitcoincore.org.

**Comment by dr-orlovsky** [comment]
Thank you for suggestions, they were used in the new release: https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.2.0
