### ISSUE TITLE
Windows GTK issue

### ISSUE THREAD

**Issue by raymonddurk** [mycitadel/mycitadel-desktop#48]
## Bug type
Put `x` in the boxes below:
- [ x] Installation issue
- [ ] App crash
- [ ] Broken UI
- [ ] Incorrect app behaviour

## Operating system
- [ ] Linux (specify distribution here)
- [ ] MacOS
- [x ] Windows

## Problem description
I tried installing the 1.0 version, didn't work. I tried again with the 1.1, still doesn't work. "The code execution cannot proceed because gdk_pixbuf-2.0.0.dll was not found. Reinstalling the program may fix this problem."

Narrator: it didn't

I was hoping it was early version bugs but figured I'd reach out this time. Let me know if you need more information or know how to install the missing package.

## Attackments

Please attach related files (wallets, PSBTs) and provide details on the involved
addresses and txid, when appropriate.

PS. Please remove this ^^ Some noob is going to read attatch wallet and upload their seed.

**Comment by Bosch-0** [comment]
Also having the exact same issue

**Comment by dr-orlovsky** [comment]
Which specific version of Windows is used? I have discovered that GTK has compatibility problems with Windows 11 which are hard to solve, but is working on Windows 10

**Comment by raymonddurk** [comment]
The machine I tried running this on was Windows 10 Enterprise build 19044.1766

**Comment by raymonddurk** [comment]
Also FYI but you misspelled attachments in the prefilled form.

**Comment by dr-orlovsky** [comment]
>> Please attach related files (wallets, PSBTs) and provide details on the involved addresses and txid, when appropriate.
> PS. Please remove this ^^ Some noob is going to read attatch wallet and upload their seed.

MyCitadel never touches a single private key; its wallet files are just descriptor + cache of tx from blockchain

**Comment by dr-orlovsky** [comment]
The issue is fixed in https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.4.0 - Windows installer installs all required GTK dependencies.

If something is not working for you, pls feel free to open a new issue (or reopen this one)
