### ISSUE TITLE
App crashes for time spending conditions

### ISSUE THREAD

**Issue by darko-321** [mycitadel/mycitadel-desktop#49]
## Bug type
Put `x` in the boxes below:
- [ ] Installation issue
- [x] App crash
- [ ] Broken UI
- [ ] Incorrect app behaviour

## Operating system
- [x] Linux (Ubuntu 20.04.4)
- [ ] MacOS
- [ ] Windows

## Problem description
For the following wallets:
Custom wallet, Company or organization wallet, Multi-sig using your devices and Hodling wallet,

When you select "starting from" as a spending condition with a date in the past, the app crashes. E.g. 31.12.2021 will crash, but 01.01.2022 will not (even though both are in the past).

## Attachments

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "property 'after-year' of type 'Condition' can't be set from given value, it is invalid or out of range", filename: "/home/mch2022/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs", function: "glib::object", line: 3393 }', /home/mch2022/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs:2238:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by dr-orlovsky** [comment]
Thanks for reporting!
