### ISSUE TITLE
Files aren't signed

### ISSUE THREAD

**Issue by perfectpassage** [mycitadel/mycitadel-desktop#51]
## Bug type
The files aren't showing any valid sigs.

## Operating system
Linux Debian 11

## Problem description

user@user:~$ gpg --verify '/home/user/Downloads/mycitadel-macos-amd64.asc' '/home/user/Downloads/mycitadel-macos-amd64' 
gpg: not a detached signature
user@user:~$ gpg --verify-options show-notations '/home/user/Downloads/mycitadel-linux-amd64' 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: no valid OpenPGP data found.
gpg: processing message failed: Unknown system error

**Comment by dr-orlovsky** [comment]
signature is in the separate file https://github.com/mycitadel/mycitadel-desktop/releases/download/v1.1.0/mycitadel-linux-amd64.asc as listed in the release assets in https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.1.0

**Comment by perfectpassage** [comment]
I've tested Mac and Linux versions.  I'm still getting the error when verifying:

**Comment by dr-orlovsky** [comment]
Fixed in the latest release: https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.2.0
