### ISSUE TITLE
Windows requirement: Python 3.11 (python311.dll)

### ISSUE THREAD

**Issue by sondreb** [mycitadel/mycitadel-desktop#92]
## Bug type
Put `x` in the boxes below:
- [ x] Installation issue
- [x ] App crash

## Operating system
- [x ] Windows

## Problem description

Launching the app on Windows 11 with Python 3.10 installed throws this error:

![image](https://user-images.githubusercontent.com/309938/235670978-447aef5d-0110-48a6-9b0a-357823abe0ab.png)

## Solution

The solution is to simply installed Python 3.11.x and it works fine.

I suggest adding some instructions somewhere to install Python 3.11 as requirement for Windows users.

**Comment by dr-orlovsky** [comment]
Thank you for the very detailed report!

The python is required by HWI we are using. We have information about that requirement in the INSTALL.md referenced from the README:

> Note that you need to have Python 3 and PIP installed. On Debian-based systems <...> For other systems, please refer to the python website for the installation instructions.

But I agree that more detailed instructions for Windows are needed.

We also plan to bundle python with installation package to remove this inconvenience in the future versions.

**Comment by sondreb** [comment]
Great thanks! Just a small note in the release info somewhere that Windows users needs Python 3.11 and link to that website will help users with even smoother experience 👍 Including dependencies is even better.

**Comment by sskras** [comment]
@dr-orlovsky commented [on May 2](https://github.com/mycitadel/mycitadel-desktop/issues/92#issuecomment-1531433271):

> The python is required by HWI we are using. We have information about that requirement in the INSTALL.md [...]:

It says:

> > ## HWI
> > 
> > If you plan to work with hardware wallets it is required to get `hwi`
> > application installed and working (this application provides an 
> > interface to hardware wallets). In order to do that please follow 
> > [the instructions from the official repository][hwi].

Could you also consider making this dependency optional, please?
Not all folks around are to use hardware wallets.

> But I agree that more detailed instructions for Windows are needed.
> 
> We also plan to bundle python with installation package to remove this inconvenience in the future versions.

Making an MINGW64-style package for MSYS2 would be a nice start:
https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-dust?repo=ucrt64

**Comment by dr-orlovsky** [comment]
> Could you also consider making this dependency optional, please?
> Not all folks around are to use hardware wallets.

I am afraid it is not possible since we can't have an optional dll dependencies in Windows... However we are working on using Python redistributable to simplify the installation.

**Comment by sskras** [comment]
> I am afraid it is not possible since we can't have an optional dll dependencies in Windows...

That's intriguing. Could you please give more detail of that?
Maybe the limitation comes from the distribution way of choice for Windows – the MSI format or the current MSI packaging tool?

**Comment by dr-orlovsky** [comment]
Fixed in https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.4.0 release: windows binary includes all Python dlls and does not require existing python installation

**Comment by dr-orlovsky** [comment]
@sskras seems that just last week Rust compiler finally added windows DLL linking improvements: https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html#raw-dylib-linking

Anyway, we solved the issue by providing a proper windows installation package, so I am making this note just in case everyone else would need it

**Comment by sskras** [comment]
Thanks for the both points.

Well, I have some doubts about bundling in the Python dlls. Eg. how do I know their origin / where did you get these binaries from.  I tried looking for that change up in the `git log`,  but see nothing related.

But that's just my concerns which probably doesn't matter much on the project's scale.

**Comment by sskras** [comment]
Thanks!
